version: '3.4'

services:

  nginx:
    build:
      context: docker/nginx
    image: ${IMAGE_NAME_PREFIX}-nginx:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - ${WEB_SERVER_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - php

  php:
    build:
      context: docker/php
    image: ${IMAGE_NAME_PREFIX}-php:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX}-php
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped

  db:
    image: mysql:5.7.26
    container_name: ${CONTAINER_NAME_PREFIX}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${NOTES_DATABASE_NAME}
      MYSQL_USER: ${NOTES_DATABASE_USER}
      MYSQL_PASSWORD: ${NOTES_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NOTES_DATABASE_PASSWORD}

  db-search:
    image: mysql:5.7.26
    container_name: ${CONTAINER_NAME_PREFIX}-db-search
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${NOTES_DATABASE_SEARCH_NAME}
      MYSQL_USER: ${NOTES_DATABASE_SEARCH_USER}
      MYSQL_PASSWORD: ${NOTES_DATABASE_SEARCH_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${NOTES_DATABASE_SEARCH_PASSWORD}
