version: '3.4'

services:

  nginx:
    build:
      context: docker/nginx
    image: ${IMAGE_NAME_PREFIX}-nginx:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX}-nginx
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - ${WEB_SERVER_PORT:-80}:80
    restart: unless-stopped
    depends_on:
      - php

  php:
    build:
      context: docker/php
    image: ${IMAGE_NAME_PREFIX}-php:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_NAME_PREFIX}-php
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped

#  mysql:
#    image: mysql:5.7.21
#    container_name: ${CONTAINER_NAME_PREFIX}-mysql
#    restart: unless-stopped
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#    ports:
#      - '3306:3306'
