version: "3.4"

x-comand: &command
  user: '${CURRENT_UID}:${CURRENT_GID}'
  volumes:
    - ./:/app
  working_dir: /app

services:

  php-cli:
    <<: *command
    image: ${IMAGE_PREFIX}-php:${IMAGE_VERSION:-latest}
    entrypoint: php

  artisan:
    <<: *command
    image: ${IMAGE_PREFIX}-php:${IMAGE_VERSION:-latest}
    entrypoint: ./artisan

  composer:
    <<: *command
    image: composer:1.9.0
    volumes:
      - ${CACHE_DIR}/composer:/opt/composer-cache
      - ./:/app
    environment:
      COMPOSER_HOME: /opt/composer-cache

  npm:
    <<: *command
    image: node:8.16.0
    entrypoint: npm
    volumes:
      - ${CACHE_DIR}/npm:/opt/npm-cache
      - ./:/app
    environment:
      npm_config_cache: /opt/npm-cache

  node:
    <<: *command
    image: node:8.16.0
    entrypoint: node
    volumes:
      - ${CACHE_DIR}/docker-cache/npm:/opt/npm-cache
      - ./:/app
    environment:
      npm_config_cache: /opt/npm-cache
