version: '3.4'

x-mysql: &mysql
  image: mysql:5.7.26
  user: '${CURRENT_UID}:${CURRENT_GID}'
  restart: unless-stopped

services:

  nginx:
    build:
      context: docker/nginx
    image: ${IMAGE_PREFIX}-nginx:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_PREFIX}-nginx
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - '${WEB_SERVER_PORT:-80}:80'
    restart: unless-stopped
    depends_on:
      - php

  php:
    build:
      context: docker/php
    image: ${IMAGE_PREFIX}-php:${IMAGE_VERSION:-latest}
    container_name: ${CONTAINER_PREFIX}-php
    user: '${CURRENT_UID}:${CURRENT_GID}'
    volumes:
      - ./:/app
    working_dir: /app
    restart: unless-stopped

  db:
    <<: *mysql
    container_name: ${CONTAINER_PREFIX}-db
    volumes:
      - ${DATA_DIR}/mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  db-search:
    <<: *mysql
    container_name: ${CONTAINER_PREFIX}-db-search
    volumes:
      - ${DATA_DIR}/mysql/db-search:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DATABASE_SEARCH_NAME}
      MYSQL_USER: ${DATABASE_SEARCH_USER}
      MYSQL_PASSWORD: ${DATABASE_SEARCH_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_SEARCH_PASSWORD}
