---
- name: Create cache directory.
  file:
    path: '{{ application_cache_dir }}'
    state: directory
    owner: '{{ application_user }}'
    mode: 0777
    recurse: yes

- name: Add nginx user to app group.
  user:
    name: www-data
    groups: '{{ application_user }}'
    append: yes

- name: Create environment variables.
  template:
    src: envs.j2
    dest: '/home/{{ application_user }}/.envs'
    owner: '{{ application_user }}'
    group: '{{ application_user }}'

- name: Add environment variables.
  lineinfile:
    dest: '/home/{{ application_user }}/.bashrc'
    line: 'source $HOME/.envs'

- name: Add cd to {{ application_root }} in shell startup file.
  lineinfile:
    dest: '/home/{{ application_user }}/.bashrc'
    line: "cd '{{ application_root }}'"
