---
- hosts: all

  vars:
    php_bin: /usr/bin/php
    app_dir: /var/www/notes
    work_dir: '{{ app_dir }}/current'

  tasks:
    - name: 'Set up shell.'
      cron:
        name: SHELL
        env: yes
        value: /bin/bash
    
    - name: 'Set up backup schedule.'
      cron:
        name: 'Backup schedule'
        minute: '0'
        hour: '0'
        job: 'source "/home/notes_owner/.envs"; {{ php_bin}} {{ work_dir }}/bin/console app:database:backup --no-interaction >{{ work_dir }}/cron.log 2>&1'
