---
- hosts: all

  vars:
    application_name: notes
    application_root: /vagrant
    application_user: ubuntu
    application_cache_dir: /var/notes/

    primary_database: '{{ application_name }}'
    search_database: '{{ application_name }}_search'

    app_envs:
      NOTES_APP_PASSWORD: password
      NOTES_SECRET_TOKEN: ThisTokenIsNotSoSecretChangeIt
      NOTES_DATABASE_HOST: 127.0.0.1
      NOTES_DATABASE_PORT: 3306
      NOTES_DATABASE_NAME: '{{ primary_database }}'
      NOTES_DATABASE_USER: '{{ primary_database }}'
      NOTES_DATABASE_PASSWORD: '{{ primary_database }}'
      NOTES_DATABASE_SEARCH_HOST: 127.0.0.1
      NOTES_DATABASE_SEARCH_PORT: 3306
      NOTES_DATABASE_SEARCH_NAME: '{{ search_database }}'
      NOTES_DATABASE_SEARCH_USER: '{{ search_database }}'
      NOTES_DATABASE_SEARCH_PASSWORD: '{{ search_database }}'
      NOTES_MAILER_HOST: 127.0.0.1
      NOTES_MAILER_PORT: 1025
      NOTES_MAILER_USER: noreply@notes.tld
      NOTES_MAILER_PASSWORD: ''
      SYMFONY_ENV: vagrant
      APP_ENV: vagrant

    # timezone settings

    timezone: UTC

    # nginx settings

    nginx_remove_default_vhost: true
    nginx_vhosts:
      - server_name: notes.loc
        template: '{{ playbook_dir }}/templates/app.vhost.j2'

    # php settings

    php_version: '7.1'
    php_packages_extra:
      - 'php{{ php_version }}-curl'
      - 'php{{ php_version }}-gd'
      - 'php{{ php_version }}-fpm'
      - 'php{{ php_version }}-mbstring'
      - 'php{{ php_version }}-xml'
      - 'php{{ php_version }}-intl'
      - 'php{{ php_version }}-zip'
      - 'php{{ php_version }}-mysql'
    php_webserver_daemon: nginx
    php_enable_php_fpm: true
    php_fpm_listen: /run/php/php{{ php_version }}-fpm.sock
    php_date_timezone: '{{ timezone }}'

    php_xdebug_version: 2.6.0

    # mysql settings

    mysql_databases:
      - name: '{{ primary_database }}'
      - name: '{{ search_database }}'
    mysql_users:
      - name: '{{ primary_database }}'
        host: '%'
        password: '{{ primary_database }}'
        priv: '{{ primary_database }}.*:ALL'
      - name: '{{ search_database }}'
        host: '%'
        password: '{{ search_database }}'
        priv: '{{ search_database }}.*:ALL'

    # nodejs settings

    nodejs_version: '8.x'

    deployer_version: "6.0.5"

  environment: '{{ app_envs }}'

  pre_tasks:
    - name: Ensure that PHP PPA is added.
      apt_repository: repo=ppa:ondrej/php state=present

    - name: Install additional packages.
      apt: package={{ item }} state=latest
      with_items:
        - make
        - git
        - curl
        - zip

  roles:
    - yatesr.timezone
    - geerlingguy.nginx
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-xdebug
    - geerlingguy.mysql
    - geerlingguy.nodejs
    - geerlingguy.composer
    - geerlingguy.mailhog
    - stevenjlho.deployer
    - application
